import * as z from 'zod'

export const zTS_TYPES = z
  .union([
    z.literal('string'),
    z.literal('number'),
    z.literal('boolean'),
    z.literal('array'),
    z.literal('object'),
    z.literal('function'),
  ])
  .nullable()

export type TS_TYPES = z.infer<typeof zTS_TYPES>

export const zCoralNameSchema = z.string().regex(/^[a-zA-Z_$][0-9a-zA-Z_$]*$/)

export const zElementSchema = z
  .enum([
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'p',
    'span',
    'a',
    'img',
    'ul',
    'li',
    'ol',
    'dl',
    'dt',
    'dd',
    'nav',
    'div',
    'section',
    'footer',
    'header',
    'button',
    'input',
    'form',
    'textarea',
    'select',
    'option',
    'table',
    'tr',
    'td',
    'th',
    'thead',
    'tbody',
    'tfoot',
    'caption',
    'time',
    'article',
    'aside',
    'main',
    'figure',
    'figcaption',
    'strong',
    'em',
    'code',
    'pre',
    'blockquote',
    'hr',
    'br',
    'label',
    'fieldset',
    'legend',
    'audio',
    'video',
    'source',
    'canvas',
    'text',
    'svg',
    'circle',
    'rect',
    'path',
    'ellipse',
    'polygon',
    'line',
    'polyline',
    'g',
    'defs',
    'use',
    'b',
    'i',
    'u',
    's',
    'small',
    'mark',
    'abbr',
    'cite',
    'kbd',
    'samp',
    'var',
    'sub',
    'sup',
  ])
  .default('div')

export type CoralElementType = z.infer<typeof zElementSchema>
